### ISSUE TITLE
Rebranding out of lleb to Farer

### ISSUE THREAD

**Issue by doamatto** [LLEB-ME/wiki#16]
lleb labs should be generally separated from the intranet branding. Through some discussions with @cyckl that can be affirmed, the current idea is:
- Change the "lleb labs intranet" to:
  - "The Farer Group"
  - "Farer"
- Establish `nic.fa` to control domains inside the Farer intranet
  - Delegate `.fa` to be owned by The Farer Group
    - Domain registration is open to any via automated request
    - `nic.fa` and name services (eg. `wiki.fa`, `music.fa`, `news.fa`) are restricted to The Farer Group  
    - `lleb.fa` restricted to lleb labs and their personnel

This will have breaking changes as all Tailscale IPs **will change** and all members and servers will have to re-authenticate with the new Tailscale organisation. This does create the optimal time to change infrastructure as we will have to, in lamest terms, "restart" the networking half of things and re-configure based on how things currently are.

As much input and feedback is needed. [Please vote appropriately](https://wiki.lleb/lleb-and-you/voting/) and aid us in a smooth transition as much as possible.

**Comment by doamatto** [comment]
Considering how stale this issue is, we need to recap on what we need to complete to mark a rebrand transition as complete.

We may also want to establish a general design guideline for Gouv.fa while we are at it for its microservices and whatever theming we may want to do to make things look more "coherent."

Thoughts, @cyckl @jackmerrill ?

**Comment by cyckl** [comment]
Most assets, services, and usernames are already using Farer branding. The only remaining straggler is just this Github organization, which is a challenge since Tailscale depends on it.

We can complete the transition now by renaming this organization and rebuilding the Tailscale network again using our saved ACLs—this wouldn't be a huge disruption mainly because the network isn't actually serving any content yet.

Of course, we can also wait until a more custom self-hosted solution that'll rely on our SSO, effectively rendering the above point moot.

**Comment by cyckl** [comment]
A design guideline / actual design system would be a smart decision since we don't have any services established yet, although implementation would differ depending on the tech stack per service. Some might already come with a built in interface and others will probably be built up from scratch. If we trend toward simple static interfaces or SSG we could likely do with just a common semantic CSS file.

**Comment by doamatto** [comment]
> A design guideline ... would be a smart decision since we don't have any services established yet

Ideally, this would be what we follow for a unique improved look for both services officially provided, where applicable, and governing websites (ie. https://gouv.fa). 

> If we trend toward simple static interfaces ... we could likely do with just a common semantic CSS file

The idea of this is great, and can definitely be applied in certain cases (ie. forms, navigation, et al.). However, some sites may have a level of specificity needed that requires deviation from these sheets to be properly functional.

It also creates further issues with version control of these styling and making sure that changes to the design "standard" would be implemented in a timely matter by those responsible. This is naturally an issue regardless, but one I feel like could either be made easier or harder with a common file to utilise.
