### ISSUE TITLE
Call for voted staff members

### ISSUE THREAD

**Issue by doamatto** [LLEB-ME/wiki#27]
To help with the growing tasklist behind Farer, a call for voted staff members. These are in essence the same as permanent staff members with little to no difference. An ideal candidate should be:
  - someone who can dedicate time to implementing, developing, documenting, or completing tasks
  - someone who is able to compose professional emails; and:
  - someone who understands, generally, how Farer works and operates.

Candidates must be Farer members. Those under the draft Trusted Individuals Scheme are not eligible for becoming staff members and must wait until they integrate as members. Currently, there are no members under this draft that are in this GitHub organisation: if you are a part of this organisation, you can be a candidate.

Those who want to become candidates will have to:
  - create a short appeal describing how they can fit the needs outlined above; and:
  - provide evidence that their appeal is credible.

Endorsing is open for all appeals as they come in. New appeals will cease 31 october, 2022 and this issue will be locked. Endorsements will continue until the end of the first week of November. Use the +1 emojis to endorse people. **A reminder to @LLEB-ME/members:** you are endorsing and recommending people to have significantly more power. Use your power well.

**Comment by doamatto** [comment]
Per yesterday's request, here's the general roles that we're looking for:
  - developers
  - individuals to contact other companies (ie. Fastly) and individuals gather feedback for improving Farer (ie. [see HN post](https://news.ycombinator.com/item?id=32266554))

**Comment by doamatto** [comment]
Rephrased terminology based on @risih "loophole" logic

**Comment by jackmerrill** [comment]
As my [personal project](https://astralapp.io) is nearing a state of stability, I am submitting my appeal for staff membership. I am proficient in Typescript, and focusing on Go. I have experience with C# and Python. I'm also a UI/UX designer, and currently attending college to study Interactive and Accessible Digital Design (tl;dr good, usable websites).  Alongside being a developer, I am an active volunteer, and current Regional Manager for [CodeDay](https://codeday.org). At CodeDay, I help organize events in my local city (in my current case, Boston) by finding venues, sponsors, mentors and judges, as well as outreach to high schools. I have been with Farer since early April (back when it was called LLEB), and have endorsed a new member (#15).

Endorsed by @iplusplus42

**Comment by cyckl** [comment]
milk

**Comment by doamatto** [comment]
I never said *when* I'd lock this.
